CREATE SCHEMA IF NOT EXISTS "pagos-pedidos";

CREATE TABLE IF NOT EXISTS "pagos-pedidos".pago (
    id integer NOT NULL,
    id_pedido integer NOT NULL,
    fecha date NOT NULL,
    monto numeric(9,0) NOT NULL,
    eliminado boolean DEFAULT false NOT NULL,
    CONSTRAINT pago_pkey PRIMARY KEY (id),
    CONSTRAINT fk_pago_pedido FOREIGN KEY (id_pedido)
        REFERENCES pedidos.pedido (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE "pagos-pedidos".pago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "pagos-pedidos".pago_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX IF NOT EXISTS idx_pago_id_pedido
    ON "pagos-pedidos".pago (id_pedido);
