--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)

-- Started on 2025-08-08 09:46:02 -03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 10 (class 2615 OID 8525775)
-- Name: auditoria; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA auditoria;


--
-- TOC entry 6 (class 2615 OID 8525391)
-- Name: auth; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA auth;


--
-- TOC entry 8 (class 2615 OID 8525491)
-- Name: facturacion; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA facturacion;


--
-- TOC entry 7 (class 2615 OID 8525435)
-- Name: inventario; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA inventario;


--
-- TOC entry 9 (class 2615 OID 8525713)
-- Name: pedidos; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA pedidos;


--
-- TOC entry 976 (class 1247 OID 8525777)
-- Name: accion_type; Type: TYPE; Schema: auditoria; Owner: -
--

CREATE TYPE auditoria.accion_type AS ENUM (
    'C',
    'M',
    'E'
);


--
-- TOC entry 3727 (class 0 OID 0)
-- Dependencies: 976
-- Name: TYPE accion_type; Type: COMMENT; Schema: auditoria; Owner: -
--

COMMENT ON TYPE auditoria.accion_type IS 'C = Crear, M = Modificar, E = Eliminar';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 271 (class 1259 OID 8525789)
-- Name: evento; Type: TABLE; Schema: auditoria; Owner: -
--

CREATE TABLE auditoria.evento (
    id bigint NOT NULL,
    id_usuario integer NOT NULL,
    fecha_hora timestamp without time zone DEFAULT now() NOT NULL,
    accion auditoria.accion_type NOT NULL,
    pk json NOT NULL,
    id_tabla smallint NOT NULL
);


--
-- TOC entry 3728 (class 0 OID 0)
-- Dependencies: 271
-- Name: COLUMN evento.pk; Type: COMMENT; Schema: auditoria; Owner: -
--

COMMENT ON COLUMN auditoria.evento.pk IS 'La clave primaria del registro protagonista del evento. Ej. Para la tabla stock: { id_deposito: 1, id_producto: 50, id_variante: 60 }';


--
-- TOC entry 273 (class 1259 OID 8525809)
-- Name: evento_detalle; Type: TABLE; Schema: auditoria; Owner: -
--

CREATE TABLE auditoria.evento_detalle (
    id bigint NOT NULL,
    id_evento bigint NOT NULL,
    atributo character varying(80) NOT NULL,
    valor_anterior text,
    valor_nuevo text
);


--
-- TOC entry 3729 (class 0 OID 0)
-- Dependencies: 273
-- Name: TABLE evento_detalle; Type: COMMENT; Schema: auditoria; Owner: -
--

COMMENT ON TABLE auditoria.evento_detalle IS 'Almacena las modificaciones de los campos para el registro en particular protagonista del evento';


--
-- TOC entry 3730 (class 0 OID 0)
-- Dependencies: 273
-- Name: COLUMN evento_detalle.atributo; Type: COMMENT; Schema: auditoria; Owner: -
--

COMMENT ON COLUMN auditoria.evento_detalle.atributo IS 'almacena la variable modificada en forma de ruta. Ej.: /nombre';


--
-- TOC entry 272 (class 1259 OID 8525808)
-- Name: evento_detalle_id_seq; Type: SEQUENCE; Schema: auditoria; Owner: -
--

ALTER TABLE auditoria.evento_detalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auditoria.evento_detalle_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 270 (class 1259 OID 8525788)
-- Name: evento_id_seq; Type: SEQUENCE; Schema: auditoria; Owner: -
--

ALTER TABLE auditoria.evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auditoria.evento_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 8525783)
-- Name: tabla_bd; Type: TABLE; Schema: auditoria; Owner: -
--

CREATE TABLE auditoria.tabla_bd (
    id smallint NOT NULL,
    esquema character varying(50) NOT NULL,
    nombre character varying(100) NOT NULL,
    "descripción" character varying(100) NOT NULL
);


--
-- TOC entry 3731 (class 0 OID 0)
-- Dependencies: 269
-- Name: COLUMN tabla_bd.esquema; Type: COMMENT; Schema: auditoria; Owner: -
--

COMMENT ON COLUMN auditoria.tabla_bd.esquema IS 'El esquema real donde se situa la base de datos. Ej.: public';


--
-- TOC entry 3732 (class 0 OID 0)
-- Dependencies: 269
-- Name: COLUMN tabla_bd.nombre; Type: COMMENT; Schema: auditoria; Owner: -
--

COMMENT ON COLUMN auditoria.tabla_bd.nombre IS 'El nombre real en la base de datos. Ej.: unidad_medida';


--
-- TOC entry 3733 (class 0 OID 0)
-- Dependencies: 269
-- Name: COLUMN tabla_bd."descripción"; Type: COMMENT; Schema: auditoria; Owner: -
--

COMMENT ON COLUMN auditoria.tabla_bd."descripción" IS 'Nombre amigable. Ej.: Unidades de medida';


--
-- TOC entry 223 (class 1259 OID 8525365)
-- Name: rol; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.rol (
    id integer NOT NULL,
    descripcion character varying(40) NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 222 (class 1259 OID 8525364)
-- Name: rol_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.rol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.rol_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 8525376)
-- Name: rol_usuario; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.rol_usuario (
    id_rol integer NOT NULL,
    id_usuario integer NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 8525357)
-- Name: usuario; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.usuario (
    id integer NOT NULL,
    nombres character varying(60) NOT NULL,
    apellidos character varying(60) NOT NULL,
    ci character varying(20) NOT NULL,
    password character varying(200) NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 220 (class 1259 OID 8525356)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: auth; Owner: -
--

ALTER TABLE auth.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.usuario_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 8525567)
-- Name: cliente; Type: TABLE; Schema: facturacion; Owner: -
--

CREATE TABLE facturacion.cliente (
    id integer NOT NULL,
    razon_social character varying(100) NOT NULL,
    ruc character varying(10),
    telefono character varying(20),
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 247 (class 1259 OID 8525566)
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: facturacion; Owner: -
--

ALTER TABLE facturacion.cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME facturacion.cliente_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 8525493)
-- Name: compra; Type: TABLE; Schema: facturacion; Owner: -
--

CREATE TABLE facturacion.compra (
    id integer NOT NULL,
    fecha date NOT NULL,
    id_proveedor integer NOT NULL,
    nro_factura character varying(20),
    credito boolean DEFAULT false NOT NULL,
    total numeric(9,0) DEFAULT 0 NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 245 (class 1259 OID 8525519)
-- Name: compra_detalle; Type: TABLE; Schema: facturacion; Owner: -
--

CREATE TABLE facturacion.compra_detalle (
    id integer NOT NULL,
    id_compra integer NOT NULL,
    id_producto integer NOT NULL,
    cantidad numeric(6,2) DEFAULT 1.0 NOT NULL,
    precio numeric(9,0) DEFAULT 0 NOT NULL,
    subtotal numeric(9,0) DEFAULT 0 NOT NULL,
    id_variante integer NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 244 (class 1259 OID 8525518)
-- Name: compra_detalle_id_seq; Type: SEQUENCE; Schema: facturacion; Owner: -
--

ALTER TABLE facturacion.compra_detalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME facturacion.compra_detalle_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 8525492)
-- Name: compra_id_seq; Type: SEQUENCE; Schema: facturacion; Owner: -
--

ALTER TABLE facturacion.compra ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME facturacion.compra_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 8525631)
-- Name: cuota; Type: TABLE; Schema: facturacion; Owner: -
--

CREATE TABLE facturacion.cuota (
    id integer NOT NULL,
    id_venta integer NOT NULL,
    nro_cuota smallint NOT NULL,
    fecha_vencimiento date NOT NULL,
    monto numeric(9,1) DEFAULT 0 NOT NULL,
    cancelado boolean DEFAULT false NOT NULL,
    nro_recibo integer,
    fecha_cancelacion date,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 254 (class 1259 OID 8525630)
-- Name: cuota_id_seq; Type: SEQUENCE; Schema: facturacion; Owner: -
--

ALTER TABLE facturacion.cuota ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME facturacion.cuota_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 8525499)
-- Name: proveedor; Type: TABLE; Schema: facturacion; Owner: -
--

CREATE TABLE facturacion.proveedor (
    id integer NOT NULL,
    razon_social character varying(100) NOT NULL,
    ruc character varying(10),
    telefono character varying(20),
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 242 (class 1259 OID 8525498)
-- Name: proveedor_id_seq; Type: SEQUENCE; Schema: facturacion; Owner: -
--

ALTER TABLE facturacion.proveedor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME facturacion.proveedor_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 8525629)
-- Name: recibo_nro_seq; Type: SEQUENCE; Schema: facturacion; Owner: -
--

CREATE SEQUENCE facturacion.recibo_nro_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 3734 (class 0 OID 0)
-- Dependencies: 253
-- Name: recibo_nro_seq; Type: SEQUENCE OWNED BY; Schema: facturacion; Owner: -
--

ALTER SEQUENCE facturacion.recibo_nro_seq OWNED BY facturacion.cuota.nro_recibo;


--
-- TOC entry 250 (class 1259 OID 8525574)
-- Name: venta; Type: TABLE; Schema: facturacion; Owner: -
--

CREATE TABLE facturacion.venta (
    id integer NOT NULL,
    fecha date NOT NULL,
    id_cliente integer NOT NULL,
    nro_factura character varying(20),
    credito boolean DEFAULT false NOT NULL,
    total numeric(9,0) DEFAULT 0 NOT NULL,
    total_descuento numeric(9,0) DEFAULT 0 NOT NULL,
    total_interes numeric(9,0) DEFAULT 0 NOT NULL,
    total_final numeric(9,0) DEFAULT 0 NOT NULL,
    total_iva_10 numeric(9,0) DEFAULT 0 NOT NULL,
    total_iva_5 numeric(9,0) DEFAULT 0 NOT NULL,
    total_exento numeric(9,9) DEFAULT 0 NOT NULL,
    cancelado boolean DEFAULT true NOT NULL,
    fecha_cancelacion date,
    total_entrega numeric(9,0) DEFAULT 0 NOT NULL,
    id_pedido integer,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 252 (class 1259 OID 8525586)
-- Name: venta_detalle; Type: TABLE; Schema: facturacion; Owner: -
--

CREATE TABLE facturacion.venta_detalle (
    id integer NOT NULL,
    id_venta integer NOT NULL,
    id_producto integer NOT NULL,
    cantidad numeric(6,2) DEFAULT 1 NOT NULL,
    precio numeric(9,0) DEFAULT 0 NOT NULL,
    subtotal numeric(9,0) DEFAULT 0 NOT NULL,
    id_variante integer NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 251 (class 1259 OID 8525585)
-- Name: venta_detalle_id_seq; Type: SEQUENCE; Schema: facturacion; Owner: -
--

ALTER TABLE facturacion.venta_detalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME facturacion.venta_detalle_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 8525573)
-- Name: venta_id_seq; Type: SEQUENCE; Schema: facturacion; Owner: -
--

ALTER TABLE facturacion.venta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME facturacion.venta_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 8525424)
-- Name: categoria; Type: TABLE; Schema: inventario; Owner: -
--

CREATE TABLE inventario.categoria (
    id integer NOT NULL,
    descripcion character varying(50) NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 3735 (class 0 OID 0)
-- Dependencies: 232
-- Name: TABLE categoria; Type: COMMENT; Schema: inventario; Owner: -
--

COMMENT ON TABLE inventario.categoria IS 'Categorias:
1 - Insumos
2 - Indumentaria deportiva
3 - Electrodomesticos';


--
-- TOC entry 231 (class 1259 OID 8525423)
-- Name: categoria_producto_id_seq; Type: SEQUENCE; Schema: inventario; Owner: -
--

ALTER TABLE inventario.categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME inventario.categoria_producto_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 8525650)
-- Name: color; Type: TABLE; Schema: inventario; Owner: -
--

CREATE TABLE inventario.color (
    id integer NOT NULL,
    descripcion character varying(20) NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 258 (class 1259 OID 8525649)
-- Name: color_id_seq; Type: SEQUENCE; Schema: inventario; Owner: -
--

ALTER TABLE inventario.color ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME inventario.color_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 8525437)
-- Name: deposito; Type: TABLE; Schema: inventario; Owner: -
--

CREATE TABLE inventario.deposito (
    id integer NOT NULL,
    descripcion character varying(50) NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 233 (class 1259 OID 8525436)
-- Name: deposito_id_seq; Type: SEQUENCE; Schema: inventario; Owner: -
--

ALTER TABLE inventario.deposito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME inventario.deposito_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 8525461)
-- Name: inventario; Type: TABLE; Schema: inventario; Owner: -
--

CREATE TABLE inventario.inventario (
    id integer NOT NULL,
    fecha date NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 239 (class 1259 OID 8525473)
-- Name: inventario_detalle; Type: TABLE; Schema: inventario; Owner: -
--

CREATE TABLE inventario.inventario_detalle (
    id integer NOT NULL,
    id_inventario integer NOT NULL,
    id_producto integer NOT NULL,
    cantidad numeric(6,2) DEFAULT 0 NOT NULL,
    diferencia numeric(6,2) DEFAULT 0 NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 238 (class 1259 OID 8525472)
-- Name: inventario_detalle_id_seq; Type: SEQUENCE; Schema: inventario; Owner: -
--

ALTER TABLE inventario.inventario_detalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME inventario.inventario_detalle_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 8525460)
-- Name: inventario_id_seq; Type: SEQUENCE; Schema: inventario; Owner: -
--

ALTER TABLE inventario.inventario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME inventario.inventario_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 8525400)
-- Name: marca; Type: TABLE; Schema: inventario; Owner: -
--

CREATE TABLE inventario.marca (
    id integer NOT NULL,
    descripcion character varying(50) NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 227 (class 1259 OID 8525399)
-- Name: marca_id_seq; Type: SEQUENCE; Schema: inventario; Owner: -
--

ALTER TABLE inventario.marca ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME inventario.marca_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 8525393)
-- Name: producto; Type: TABLE; Schema: inventario; Owner: -
--

CREATE TABLE inventario.producto (
    id integer NOT NULL,
    descripcion character varying(100) NOT NULL,
    precio numeric(9,0) DEFAULT 0 NOT NULL,
    id_marca integer,
    id_tipo integer NOT NULL,
    id_categoria integer NOT NULL,
    unidad_medida character varying(3) NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 225 (class 1259 OID 8525392)
-- Name: producto_id_seq; Type: SEQUENCE; Schema: inventario; Owner: -
--

ALTER TABLE inventario.producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME inventario.producto_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 262 (class 1259 OID 8525675)
-- Name: producto_variante; Type: TABLE; Schema: inventario; Owner: -
--

CREATE TABLE inventario.producto_variante (
    id_producto integer NOT NULL,
    id_variante integer NOT NULL,
    precio numeric(9,0) DEFAULT 0 NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 235 (class 1259 OID 8525443)
-- Name: stock; Type: TABLE; Schema: inventario; Owner: -
--

CREATE TABLE inventario.stock (
    id_deposito integer NOT NULL,
    id_producto integer NOT NULL,
    cantidad numeric(6,2) DEFAULT 0 NOT NULL,
    ultima_actualizacion date NOT NULL,
    cantidad_minima numeric(6,2) DEFAULT 0 NOT NULL,
    id_variante integer NOT NULL
);


--
-- TOC entry 257 (class 1259 OID 8525643)
-- Name: tamanio; Type: TABLE; Schema: inventario; Owner: -
--

CREATE TABLE inventario.tamanio (
    id integer NOT NULL,
    descripcion character varying(20) NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 256 (class 1259 OID 8525642)
-- Name: tamanio_id_seq; Type: SEQUENCE; Schema: inventario; Owner: -
--

ALTER TABLE inventario.tamanio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME inventario.tamanio_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 8525407)
-- Name: tipo; Type: TABLE; Schema: inventario; Owner: -
--

CREATE TABLE inventario.tipo (
    id integer NOT NULL,
    descripcion character varying(50) NOT NULL,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 229 (class 1259 OID 8525406)
-- Name: tipo_producto_id_seq; Type: SEQUENCE; Schema: inventario; Owner: -
--

ALTER TABLE inventario.tipo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME inventario.tipo_producto_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 8525657)
-- Name: variante; Type: TABLE; Schema: inventario; Owner: -
--

CREATE TABLE inventario.variante (
    id integer NOT NULL,
    id_tamanio integer NOT NULL,
    id_color integer NOT NULL,
    descripcion character varying(100),
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 260 (class 1259 OID 8525656)
-- Name: variante_id_seq; Type: SEQUENCE; Schema: inventario; Owner: -
--

ALTER TABLE inventario.variante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME inventario.variante_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 264 (class 1259 OID 8525715)
-- Name: pedido; Type: TABLE; Schema: pedidos; Owner: -
--

CREATE TABLE pedidos.pedido (
    id integer NOT NULL,
    fecha_pedido date NOT NULL,
    fecha_confirmacion date,
    fecha_entrega date,
    confirmado boolean DEFAULT false NOT NULL,
    entregado boolean DEFAULT false NOT NULL,
    id_cliente integer NOT NULL,
    total numeric(9,0) NOT NULL,
    id_venta integer,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 266 (class 1259 OID 8525724)
-- Name: pedido_detalle; Type: TABLE; Schema: pedidos; Owner: -
--

CREATE TABLE pedidos.pedido_detalle (
    id integer NOT NULL,
    id_pedido integer NOT NULL,
    id_producto integer NOT NULL,
    id_variante integer NOT NULL,
    cantidad numeric(6,2) DEFAULT 1 NOT NULL,
    precio numeric(9,0) DEFAULT 0 NOT NULL,
    subtotal numeric(9,0) DEFAULT 0 NOT NULL,
    descripcion text,
    eliminado boolean DEFAULT false NOT NULL
);


--
-- TOC entry 265 (class 1259 OID 8525723)
-- Name: pedido_detalle_id_seq; Type: SEQUENCE; Schema: pedidos; Owner: -
--

ALTER TABLE pedidos.pedido_detalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pedidos.pedido_detalle_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 263 (class 1259 OID 8525714)
-- Name: pedido_id_seq; Type: SEQUENCE; Schema: pedidos; Owner: -
--

ALTER TABLE pedidos.pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pedidos.pedido_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 268 (class 1259 OID 8525746)
-- Name: pedido_imagen; Type: TABLE; Schema: pedidos; Owner: -
--

CREATE TABLE pedidos.pedido_imagen (
    id integer NOT NULL,
    id_pedido integer NOT NULL,
    descripcion text
);


--
-- TOC entry 267 (class 1259 OID 8525745)
-- Name: pedido_imagen_id_seq; Type: SEQUENCE; Schema: pedidos; Owner: -
--

ALTER TABLE pedidos.pedido_imagen ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pedidos.pedido_imagen_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 8525547)
-- Name: unidad_medida; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unidad_medida (
    id character varying(3) NOT NULL,
    descripcion_singular character varying(20) NOT NULL,
    descripcion_plural character varying(20) NOT NULL,
    abreviatura_singular character varying(5) NOT NULL,
    abreviatura_plural character varying(5) NOT NULL
);


--
-- TOC entry 3736 (class 0 OID 0)
-- Dependencies: 246
-- Name: COLUMN unidad_medida.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.unidad_medida.id IS 'Ej: UN = Unidades, MT = Metros';


--
-- TOC entry 3549 (class 2606 OID 8525815)
-- Name: evento_detalle evento_detalle_pkey; Type: CONSTRAINT; Schema: auditoria; Owner: -
--

ALTER TABLE ONLY auditoria.evento_detalle
    ADD CONSTRAINT evento_detalle_pkey PRIMARY KEY (id);


--
-- TOC entry 3547 (class 2606 OID 8525796)
-- Name: evento evento_pkey; Type: CONSTRAINT; Schema: auditoria; Owner: -
--

ALTER TABLE ONLY auditoria.evento
    ADD CONSTRAINT evento_pkey PRIMARY KEY (id);


--
-- TOC entry 3545 (class 2606 OID 8525787)
-- Name: tabla_bd tabla_bd_pkey; Type: CONSTRAINT; Schema: auditoria; Owner: -
--

ALTER TABLE ONLY auditoria.tabla_bd
    ADD CONSTRAINT tabla_bd_pkey PRIMARY KEY (id);


--
-- TOC entry 3493 (class 2606 OID 8525370)
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (id);


--
-- TOC entry 3495 (class 2606 OID 8525380)
-- Name: rol_usuario rol_usuario_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.rol_usuario
    ADD CONSTRAINT rol_usuario_pkey PRIMARY KEY (id_rol, id_usuario);


--
-- TOC entry 3491 (class 2606 OID 8525363)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 3521 (class 2606 OID 8525572)
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: facturacion; Owner: -
--

ALTER TABLE ONLY facturacion.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


--
-- TOC entry 3517 (class 2606 OID 8525527)
-- Name: compra_detalle compra_detalle_pkey; Type: CONSTRAINT; Schema: facturacion; Owner: -
--

ALTER TABLE ONLY facturacion.compra_detalle
    ADD CONSTRAINT compra_detalle_pkey PRIMARY KEY (id);


--
-- TOC entry 3513 (class 2606 OID 8525497)
-- Name: compra compra_pkey; Type: CONSTRAINT; Schema: facturacion; Owner: -
--

ALTER TABLE ONLY facturacion.compra
    ADD CONSTRAINT compra_pkey PRIMARY KEY (id);


--
-- TOC entry 3527 (class 2606 OID 8525638)
-- Name: cuota cuota_pkey; Type: CONSTRAINT; Schema: facturacion; Owner: -
--

ALTER TABLE ONLY facturacion.cuota
    ADD CONSTRAINT cuota_pkey PRIMARY KEY (id);


--
-- TOC entry 3515 (class 2606 OID 8525504)
-- Name: proveedor proveedor_pkey; Type: CONSTRAINT; Schema: facturacion; Owner: -
--

ALTER TABLE ONLY facturacion.proveedor
    ADD CONSTRAINT proveedor_pkey PRIMARY KEY (id);


--
-- TOC entry 3525 (class 2606 OID 8525594)
-- Name: venta_detalle venta_detalle_pkey; Type: CONSTRAINT; Schema: facturacion; Owner: -
--

ALTER TABLE ONLY facturacion.venta_detalle
    ADD CONSTRAINT venta_detalle_pkey PRIMARY KEY (id);


--
-- TOC entry 3523 (class 2606 OID 8525583)
-- Name: venta venta_pkey; Type: CONSTRAINT; Schema: facturacion; Owner: -
--

ALTER TABLE ONLY facturacion.venta
    ADD CONSTRAINT venta_pkey PRIMARY KEY (id);


--
-- TOC entry 3503 (class 2606 OID 8525429)
-- Name: categoria categoria_producto_pkey; Type: CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.categoria
    ADD CONSTRAINT categoria_producto_pkey PRIMARY KEY (id);


--
-- TOC entry 3531 (class 2606 OID 8525655)
-- Name: color color_pkey; Type: CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.color
    ADD CONSTRAINT color_pkey PRIMARY KEY (id);


--
-- TOC entry 3505 (class 2606 OID 8525442)
-- Name: deposito deposito_pkey; Type: CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.deposito
    ADD CONSTRAINT deposito_pkey PRIMARY KEY (id);


--
-- TOC entry 3511 (class 2606 OID 8525480)
-- Name: inventario_detalle inventario_detalle_pkey; Type: CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.inventario_detalle
    ADD CONSTRAINT inventario_detalle_pkey PRIMARY KEY (id);


--
-- TOC entry 3509 (class 2606 OID 8525466)
-- Name: inventario inventario_pkey; Type: CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.inventario
    ADD CONSTRAINT inventario_pkey PRIMARY KEY (id);


--
-- TOC entry 3499 (class 2606 OID 8525405)
-- Name: marca marca_pkey; Type: CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.marca
    ADD CONSTRAINT marca_pkey PRIMARY KEY (id);


--
-- TOC entry 3497 (class 2606 OID 8525398)
-- Name: producto producto_pkey; Type: CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY (id);


--
-- TOC entry 3537 (class 2606 OID 8525681)
-- Name: producto_variante producto_variante_pkey; Type: CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.producto_variante
    ADD CONSTRAINT producto_variante_pkey PRIMARY KEY (id_producto, id_variante);


--
-- TOC entry 3507 (class 2606 OID 8525695)
-- Name: stock stock_pkey; Type: CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.stock
    ADD CONSTRAINT stock_pkey PRIMARY KEY (id_deposito, id_producto, id_variante);


--
-- TOC entry 3529 (class 2606 OID 8525648)
-- Name: tamanio tamanio_pkey; Type: CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.tamanio
    ADD CONSTRAINT tamanio_pkey PRIMARY KEY (id);


--
-- TOC entry 3501 (class 2606 OID 8525412)
-- Name: tipo tipo_producto_pkey; Type: CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.tipo
    ADD CONSTRAINT tipo_producto_pkey PRIMARY KEY (id);


--
-- TOC entry 3533 (class 2606 OID 8525664)
-- Name: variante unique_variante_atributos; Type: CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.variante
    ADD CONSTRAINT unique_variante_atributos UNIQUE (id_tamanio, id_color);


--
-- TOC entry 3535 (class 2606 OID 8525662)
-- Name: variante variante_pkey; Type: CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.variante
    ADD CONSTRAINT variante_pkey PRIMARY KEY (id);


--
-- TOC entry 3541 (class 2606 OID 8525734)
-- Name: pedido_detalle pedido_detalle_pkey; Type: CONSTRAINT; Schema: pedidos; Owner: -
--

ALTER TABLE ONLY pedidos.pedido_detalle
    ADD CONSTRAINT pedido_detalle_pkey PRIMARY KEY (id, id_pedido);


--
-- TOC entry 3543 (class 2606 OID 8525752)
-- Name: pedido_imagen pedido_imagen_pkey; Type: CONSTRAINT; Schema: pedidos; Owner: -
--

ALTER TABLE ONLY pedidos.pedido_imagen
    ADD CONSTRAINT pedido_imagen_pkey PRIMARY KEY (id);


--
-- TOC entry 3539 (class 2606 OID 8525722)
-- Name: pedido pedido_pkey; Type: CONSTRAINT; Schema: pedidos; Owner: -
--

ALTER TABLE ONLY pedidos.pedido
    ADD CONSTRAINT pedido_pkey PRIMARY KEY (id);


--
-- TOC entry 3519 (class 2606 OID 8525551)
-- Name: unidad_medida unidad_medida_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unidad_medida
    ADD CONSTRAINT unidad_medida_pkey PRIMARY KEY (id);


--
-- TOC entry 3578 (class 2606 OID 8525816)
-- Name: evento_detalle fk_evento_detalle_evento; Type: FK CONSTRAINT; Schema: auditoria; Owner: -
--

ALTER TABLE ONLY auditoria.evento_detalle
    ADD CONSTRAINT fk_evento_detalle_evento FOREIGN KEY (id_evento) REFERENCES auditoria.evento(id);


--
-- TOC entry 3576 (class 2606 OID 8525802)
-- Name: evento fk_evento_tabla_bd; Type: FK CONSTRAINT; Schema: auditoria; Owner: -
--

ALTER TABLE ONLY auditoria.evento
    ADD CONSTRAINT fk_evento_tabla_bd FOREIGN KEY (id) REFERENCES auditoria.tabla_bd(id);


--
-- TOC entry 3577 (class 2606 OID 8525797)
-- Name: evento fk_evento_usuario; Type: FK CONSTRAINT; Schema: auditoria; Owner: -
--

ALTER TABLE ONLY auditoria.evento
    ADD CONSTRAINT fk_evento_usuario FOREIGN KEY (id_usuario) REFERENCES auth.usuario(id);


--
-- TOC entry 3550 (class 2606 OID 8525386)
-- Name: rol_usuario fk_rol_usuario_rol; Type: FK CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.rol_usuario
    ADD CONSTRAINT fk_rol_usuario_rol FOREIGN KEY (id_rol) REFERENCES auth.rol(id);


--
-- TOC entry 3551 (class 2606 OID 8525381)
-- Name: rol_usuario fk_rol_usuario_usuario; Type: FK CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.rol_usuario
    ADD CONSTRAINT fk_rol_usuario_usuario FOREIGN KEY (id_usuario) REFERENCES auth.usuario(id);


--
-- TOC entry 3561 (class 2606 OID 8525528)
-- Name: compra_detalle fk_compra_detalle_compra; Type: FK CONSTRAINT; Schema: facturacion; Owner: -
--

ALTER TABLE ONLY facturacion.compra_detalle
    ADD CONSTRAINT fk_compra_detalle_compra FOREIGN KEY (id_compra) REFERENCES facturacion.compra(id);


--
-- TOC entry 3562 (class 2606 OID 8525702)
-- Name: compra_detalle fk_compra_detalle_producto_variante; Type: FK CONSTRAINT; Schema: facturacion; Owner: -
--

ALTER TABLE ONLY facturacion.compra_detalle
    ADD CONSTRAINT fk_compra_detalle_producto_variante FOREIGN KEY (id_producto, id_variante) REFERENCES inventario.producto_variante(id_producto, id_variante) NOT VALID;


--
-- TOC entry 3560 (class 2606 OID 8525508)
-- Name: compra fk_compra_proveedor; Type: FK CONSTRAINT; Schema: facturacion; Owner: -
--

ALTER TABLE ONLY facturacion.compra
    ADD CONSTRAINT fk_compra_proveedor FOREIGN KEY (id_proveedor) REFERENCES facturacion.proveedor(id) NOT VALID;


--
-- TOC entry 3563 (class 2606 OID 8525610)
-- Name: venta fk_venta_cliente; Type: FK CONSTRAINT; Schema: facturacion; Owner: -
--

ALTER TABLE ONLY facturacion.venta
    ADD CONSTRAINT fk_venta_cliente FOREIGN KEY (id_cliente) REFERENCES facturacion.cliente(id) NOT VALID;


--
-- TOC entry 3565 (class 2606 OID 8525708)
-- Name: venta_detalle fk_venta_detalle_producto_variante; Type: FK CONSTRAINT; Schema: facturacion; Owner: -
--

ALTER TABLE ONLY facturacion.venta_detalle
    ADD CONSTRAINT fk_venta_detalle_producto_variante FOREIGN KEY (id_producto, id_variante) REFERENCES inventario.producto_variante(id_producto, id_variante) NOT VALID;


--
-- TOC entry 3566 (class 2606 OID 8525595)
-- Name: venta_detalle fk_venta_detalle_venta; Type: FK CONSTRAINT; Schema: facturacion; Owner: -
--

ALTER TABLE ONLY facturacion.venta_detalle
    ADD CONSTRAINT fk_venta_detalle_venta FOREIGN KEY (id_venta) REFERENCES facturacion.venta(id);


--
-- TOC entry 3564 (class 2606 OID 8525770)
-- Name: venta fk_venta_pedido; Type: FK CONSTRAINT; Schema: facturacion; Owner: -
--

ALTER TABLE ONLY facturacion.venta
    ADD CONSTRAINT fk_venta_pedido FOREIGN KEY (id_pedido) REFERENCES pedidos.pedido(id) NOT VALID;


--
-- TOC entry 3558 (class 2606 OID 8525481)
-- Name: inventario_detalle fk_inventario_detalle_inventario; Type: FK CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.inventario_detalle
    ADD CONSTRAINT fk_inventario_detalle_inventario FOREIGN KEY (id_inventario) REFERENCES inventario.inventario(id);


--
-- TOC entry 3559 (class 2606 OID 8525486)
-- Name: inventario_detalle fk_inventario_detalle_producto; Type: FK CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.inventario_detalle
    ADD CONSTRAINT fk_inventario_detalle_producto FOREIGN KEY (id_producto) REFERENCES inventario.producto(id);


--
-- TOC entry 3552 (class 2606 OID 8525430)
-- Name: producto fk_producto_categoria; Type: FK CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.producto
    ADD CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES inventario.categoria(id) NOT VALID;


--
-- TOC entry 3553 (class 2606 OID 8525413)
-- Name: producto fk_producto_marca; Type: FK CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.producto
    ADD CONSTRAINT fk_producto_marca FOREIGN KEY (id_marca) REFERENCES inventario.marca(id) NOT VALID;


--
-- TOC entry 3554 (class 2606 OID 8525418)
-- Name: producto fk_producto_tipo; Type: FK CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.producto
    ADD CONSTRAINT fk_producto_tipo FOREIGN KEY (id_tipo) REFERENCES inventario.tipo(id) NOT VALID;


--
-- TOC entry 3555 (class 2606 OID 8525561)
-- Name: producto fk_producto_unidad_medida; Type: FK CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.producto
    ADD CONSTRAINT fk_producto_unidad_medida FOREIGN KEY (unidad_medida) REFERENCES public.unidad_medida(id) NOT VALID;


--
-- TOC entry 3569 (class 2606 OID 8525682)
-- Name: producto_variante fk_producto_variante_producto; Type: FK CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.producto_variante
    ADD CONSTRAINT fk_producto_variante_producto FOREIGN KEY (id_producto) REFERENCES inventario.producto(id);


--
-- TOC entry 3570 (class 2606 OID 8525687)
-- Name: producto_variante fk_producto_variante_variante; Type: FK CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.producto_variante
    ADD CONSTRAINT fk_producto_variante_variante FOREIGN KEY (id_variante) REFERENCES inventario.variante(id);


--
-- TOC entry 3556 (class 2606 OID 8525450)
-- Name: stock fk_stock_deposito; Type: FK CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.stock
    ADD CONSTRAINT fk_stock_deposito FOREIGN KEY (id_deposito) REFERENCES inventario.deposito(id);


--
-- TOC entry 3557 (class 2606 OID 8525696)
-- Name: stock fk_stock_producto_variante; Type: FK CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.stock
    ADD CONSTRAINT fk_stock_producto_variante FOREIGN KEY (id_producto, id_variante) REFERENCES inventario.producto_variante(id_producto, id_variante) NOT VALID;


--
-- TOC entry 3567 (class 2606 OID 8525670)
-- Name: variante fk_variante_color; Type: FK CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.variante
    ADD CONSTRAINT fk_variante_color FOREIGN KEY (id_color) REFERENCES inventario.color(id);


--
-- TOC entry 3568 (class 2606 OID 8525665)
-- Name: variante fk_variante_tamanio; Type: FK CONSTRAINT; Schema: inventario; Owner: -
--

ALTER TABLE ONLY inventario.variante
    ADD CONSTRAINT fk_variante_tamanio FOREIGN KEY (id_tamanio) REFERENCES inventario.tamanio(id);


--
-- TOC entry 3571 (class 2606 OID 8525759)
-- Name: pedido fk_pedido_cliente; Type: FK CONSTRAINT; Schema: pedidos; Owner: -
--

ALTER TABLE ONLY pedidos.pedido
    ADD CONSTRAINT fk_pedido_cliente FOREIGN KEY (id_cliente) REFERENCES facturacion.cliente(id) NOT VALID;


--
-- TOC entry 3573 (class 2606 OID 8525740)
-- Name: pedido_detalle fk_pedido_detalle_pedido; Type: FK CONSTRAINT; Schema: pedidos; Owner: -
--

ALTER TABLE ONLY pedidos.pedido_detalle
    ADD CONSTRAINT fk_pedido_detalle_pedido FOREIGN KEY (id_pedido) REFERENCES pedidos.pedido(id);


--
-- TOC entry 3574 (class 2606 OID 8525735)
-- Name: pedido_detalle fk_pedido_detalle_producto_variante; Type: FK CONSTRAINT; Schema: pedidos; Owner: -
--

ALTER TABLE ONLY pedidos.pedido_detalle
    ADD CONSTRAINT fk_pedido_detalle_producto_variante FOREIGN KEY (id_producto, id_variante) REFERENCES inventario.producto_variante(id_producto, id_variante);


--
-- TOC entry 3575 (class 2606 OID 8525753)
-- Name: pedido_imagen fk_pedido_imagen_pedido; Type: FK CONSTRAINT; Schema: pedidos; Owner: -
--

ALTER TABLE ONLY pedidos.pedido_imagen
    ADD CONSTRAINT fk_pedido_imagen_pedido FOREIGN KEY (id_pedido) REFERENCES pedidos.pedido(id);


--
-- TOC entry 3572 (class 2606 OID 8525764)
-- Name: pedido fk_pedido_venta; Type: FK CONSTRAINT; Schema: pedidos; Owner: -
--

ALTER TABLE ONLY pedidos.pedido
    ADD CONSTRAINT fk_pedido_venta FOREIGN KEY (id_venta) REFERENCES facturacion.venta(id) NOT VALID;


-- Completed on 2025-08-08 09:46:02 -03

--
-- PostgreSQL database dump complete
--

