-- Numeración correlativa de comprobantes.
-- La API la incrementa con un UPDATE dentro de la misma transacción que emite el comprobante:
-- el bloqueo de fila serializa las emisiones y un rollback devuelve el número, por lo que no quedan huecos.
CREATE TABLE IF NOT EXISTS "pagos-pedidos".numeracion (
    codigo character varying(20) NOT NULL,
    ultimo_numero integer DEFAULT 0 NOT NULL,
    CONSTRAINT numeracion_pkey PRIMARY KEY (codigo)
);

-- Recibo emitido por cada pago. Es una copia fija: los saldos son los del momento de la emisión
-- y los datos del cliente se copian para que una reimpresión muestre lo mismo que el original.
CREATE TABLE IF NOT EXISTS "pagos-pedidos".recibo (
    id integer NOT NULL,
    numero integer NOT NULL,
    id_pago integer NOT NULL,
    id_pedido integer NOT NULL,
    fecha_emision timestamp with time zone NOT NULL,
    fecha_pago date NOT NULL,
    monto numeric(9,0) NOT NULL,
    total_pedido numeric(9,0) NOT NULL,
    saldo_anterior numeric(9,0) NOT NULL,
    saldo_posterior numeric(9,0) NOT NULL,
    cliente_razon_social character varying(100) NOT NULL,
    cliente_ruc character varying(10),
    generado_por_migracion boolean DEFAULT false NOT NULL,
    anulado boolean DEFAULT false NOT NULL,
    fecha_anulacion timestamp with time zone,
    motivo_anulacion text,
    CONSTRAINT recibo_pkey PRIMARY KEY (id),
    CONSTRAINT uq_recibo_numero UNIQUE (numero),
    CONSTRAINT uq_recibo_pago UNIQUE (id_pago),
    CONSTRAINT fk_recibo_pago FOREIGN KEY (id_pago)
        REFERENCES "pagos-pedidos".pago (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_recibo_pedido FOREIGN KEY (id_pedido)
        REFERENCES pedidos.pedido (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT chk_recibo_saldos CHECK (saldo_posterior = saldo_anterior - monto),
    CONSTRAINT chk_recibo_anulacion CHECK (
        (anulado AND fecha_anulacion IS NOT NULL AND motivo_anulacion IS NOT NULL)
        OR (NOT anulado AND fecha_anulacion IS NULL AND motivo_anulacion IS NULL)
    )
);

ALTER TABLE "pagos-pedidos".recibo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "pagos-pedidos".recibo_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX IF NOT EXISTS idx_recibo_id_pedido
    ON "pagos-pedidos".recibo (id_pedido);

-- Historial de movimientos del saldo de cada pedido (emisiones y anulaciones de recibos).
-- Ordenados por id dentro de un pedido, el saldo_anterior de cada movimiento es el saldo_posterior del anterior.
CREATE TABLE IF NOT EXISTS "pagos-pedidos".movimiento_saldo (
    id integer NOT NULL,
    id_pedido integer NOT NULL,
    id_recibo integer NOT NULL,
    tipo character varying(10) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    monto numeric(9,0) NOT NULL,
    saldo_anterior numeric(9,0) NOT NULL,
    saldo_posterior numeric(9,0) NOT NULL,
    CONSTRAINT movimiento_saldo_pkey PRIMARY KEY (id),
    CONSTRAINT uq_movimiento_saldo_recibo_tipo UNIQUE (id_recibo, tipo),
    CONSTRAINT fk_movimiento_saldo_pedido FOREIGN KEY (id_pedido)
        REFERENCES pedidos.pedido (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_movimiento_saldo_recibo FOREIGN KEY (id_recibo)
        REFERENCES "pagos-pedidos".recibo (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT chk_movimiento_saldo_tipo CHECK (tipo IN ('EMISION', 'ANULACION')),
    CONSTRAINT chk_movimiento_saldo_saldos CHECK (
        (tipo = 'EMISION' AND saldo_posterior = saldo_anterior - monto)
        OR (tipo = 'ANULACION' AND saldo_posterior = saldo_anterior + monto)
    )
);

ALTER TABLE "pagos-pedidos".movimiento_saldo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "pagos-pedidos".movimiento_saldo_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX IF NOT EXISTS idx_movimiento_saldo_id_pedido
    ON "pagos-pedidos".movimiento_saldo (id_pedido);

-- Resincroniza el saldo de los pedidos con sus pagos vigentes antes de generar los recibos.
UPDATE pedidos.pedido p
SET saldo = p.total - COALESCE((
    SELECT SUM(pg.monto)
    FROM "pagos-pedidos".pago pg
    WHERE pg.id_pedido = p.id
      AND pg.eliminado = false
), 0);

-- Recibos de los pagos vigentes ya registrados.
-- No existe un saldo "al momento de emitir" para ellos, así que se calcula una única vez en orden
-- cronológico (fecha, id) por pedido. La numeración sigue el mismo orden a nivel global.
INSERT INTO "pagos-pedidos".recibo (
    numero, id_pago, id_pedido, fecha_emision, fecha_pago, monto, total_pedido,
    saldo_anterior, saldo_posterior, cliente_razon_social, cliente_ruc, generado_por_migracion
)
SELECT
    ROW_NUMBER() OVER (ORDER BY pg.fecha, pg.id),
    pg.id,
    pg.id_pedido,
    now(),
    pg.fecha,
    pg.monto,
    pe.total,
    pe.total - SUM(pg.monto) OVER pagos_previos + pg.monto,
    pe.total - SUM(pg.monto) OVER pagos_previos,
    c.razon_social,
    c.ruc,
    true
FROM "pagos-pedidos".pago pg
JOIN pedidos.pedido pe ON pe.id = pg.id_pedido
JOIN facturacion.cliente c ON c.id = pe.id_cliente
WHERE pg.eliminado = false
WINDOW pagos_previos AS (PARTITION BY pg.id_pedido ORDER BY pg.fecha, pg.id ROWS UNBOUNDED PRECEDING);

INSERT INTO "pagos-pedidos".movimiento_saldo (
    id_pedido, id_recibo, tipo, fecha, monto, saldo_anterior, saldo_posterior
)
SELECT r.id_pedido, r.id, 'EMISION', r.fecha_emision, r.monto, r.saldo_anterior, r.saldo_posterior
FROM "pagos-pedidos".recibo r
ORDER BY r.numero;

INSERT INTO "pagos-pedidos".numeracion (codigo, ultimo_numero)
SELECT 'RECIBO', COALESCE(MAX(r.numero), 0)
FROM "pagos-pedidos".recibo r;
